apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
        - image: anzeo/shopping-cart:2022-12-04-21-42-12
          name: shopping-cart
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://mouse.db.elephantsql.com/lihfuoex
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: lihfuoex
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopping-cart-db-pass
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: shopping-cart
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: shopping-cart