apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart
  template:
    metadata:
      labels:
        app: shopping-cart
    spec:
      containers:
        - image: anzeo/shopping-cart:latest
          name: shopping-cart
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://mouse.db.elephantsql.com/lihfuoex
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: lihfuoex
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopping-cart-db-pass
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8080
              name: shopping-cart-port
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: shopping-cart-port
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: shopping-cart-port
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: shopping-cart
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: shopping-cart-port
  selector:
    app: shopping-cart